spring:
  profiles: dev

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    root: DEBUG

datasource:
  url: jdbc:oracle:thin:@localhost:1521:orcl
  username: eks_db
  password: password
