spring:
  profiles:
    active: dev

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      topic-id: topic_id
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

    consumer:
      bootstrap-servers: localhost:9092
      group-id: group_id
      topic-id: topic_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password

logging:
  pattern:
    console: "%msg%n"
    level:
      root: info

